# List 1
list1 = [
    "solenoid valve",
    "control valve",
    "pneumatic",
    "mid-arrow",
    "gate valve",
    "powered valve",
    "axial compressor",
    "centrifugal compressor",
    "reciprocation compressor",
    "rotary compressor",
    "positive displacement",
    "overhead conveyor",
    "scraper conveyor",
    "screw conveyor",
    "conveyor",
    "elevator",
    "hoist",
    "skip hoist",
    "motor",
    "diesel motor",
    "electric motor",
    "liquid ring vacuum",
    "turbine driver",
    "double flow turbine",
    "agitator / mixer",
    "drum",
    "tank",
    "centrifugal blower",
    "alkylation",
    "boom loader",
    "fluid catalytic cracking",
    "fluid cooking",
    "fluidized reactor",
    "tubular",
    "reformer",
    "mixing reactor",
    "hydrodesulfurization",
    "plate tower",
    "hydro cracking",
    "packed tower",
    "chimney tower",
    "furnace",
    "counterflow forced draft",
    "counterflow natural draft",
    "crossflow inducted",
    "oil burner",
    "automatic stoker",
    "boiler",
    "reboiler",
    "condenser",
    "evaporative condenser",
    "cooling tower",
    "heat exchanger",
    "air cooled exchanger",
    "hairpin exchanger",
    "plate and frame heat exchanger",
    "spiral heat exchanger",
    "u-tube heat exchanger",
    "double pipe heat",
    "shell and tube heat",
    "single pass heat",
    "heater",
    "indicator 1",
    "indicator 2",
    "indicator 3",
    "indicator 4",
    "indicator",
    "shared indicator",
    "shared indicator 2",
    "computer indicator",
    "programmable indicator",
    "temp indicator",
    "temp transmitter",
    "temp recorder",
    "temp controller",
    "flow indicator",
    "flow transmitter",
    "flow recorder",
    "flow controller",
    "level indicator",
    "level transmitter",
    "level recorder",
    "level controller",
    "pressure transmitter",
    "pressure recorder",
    "pressure controller",
    "pressure indicator",
    "pressure recording",
    "level alarm",
    "flow element",
    "temperature element",
    "level gauge",
    "analyzer transmitter",
    "transducer",
    "one to many",
    "multi-lines",
    "butt weld",
    "top to top",
    "sonic signal",
    "nuclear",
    "hydraulic signal line",
    "mechanical link",
    "soldered/solvent",
    "double containment",
    "flange",
    "flange 2",
    "end cap",
    "end cap 2",
    "breather",
    "electronically insulated",
    "reducer",
    "inline mixer",
    "separator",
    "drain silencer",
    "triangle separator",
    "triangle separator 2",
    "tundish",
    "open vent",
    "pulsation dampener",
    "duplex strainer",
    "basket strainer",
    "vent silencer",
    "inline silencer",
    "steam trap",
    "desuperheater",
    "ejector/eductor",
    "exhaust head",
    "rotary valve",
    "expansion joint",
    "ejector/injector",
    "compressor/turbine",
    "motor driven turbine",
    "triple fan blades",
    "fan blades",
    "centrifugal pump",
    "gear pump",
    "horizontal pump",
    "progressive cavity pump",
    "screw pump",
    "sump pump",
    "vacuum pump",
    "vertical pump",
    "globe valve",
    "back pressure",
    "needle valve",
    "butterfly valve",
    "ball valve",
    "diaphragm",
    "plug valve",
    "check valve",
    "check valve 2",
    "angle valve",
    "hydraulic valve",
    "motor-operated valve",
    "float-operated valve",
    "3-way plug valve",
    "4-way valve",
    "gauge",
    "bleeder valve",
    "orifice",
    "rotameter",
    "vessel",
    "open tank",
    "open top tank",
    "closed tank",
    "storage sphere",
    "column",
    "tank 2",
    "tray column",
    "gas holder",
    "clarifier",
    "gas cylinder",
    "bag",
    "reaction vessel",
    "bin",
    "dome roof tank",
    "cone roof tank",
    "internal floating roof",
    "double wall tank",
    "onion tank",
    "indicator 5",
    "removable spool",
    "y type strainer",
    "siphon drain",
    "diverter valve",
    "detonation arrester",
    "bursting disc",
    "flame arrester",
    "flame arrester 2",
    "loadcell",
    "docking station",
    "metal check",
    "changeover valve",
    "dust filter",
    "rotary sieve",
    "air dryer",
    "drain",
    "vacuum filter",
    "buffer belt conveyor",
    "belt conveyor with metalcheck",
    "big-bag filling machine",
    "belt conveyor",
    "bag filling station",
    "mill",
    "heater",
    "filter",
    "cooling screw conveyor",
    "dust extractor",
    "indicator",
    "air filter or strainer",
    "air filter",
    "air lubricator",
    "air vent with flame arrestor",
    "bellmouth",
    "blower",
    "bulkhead penetration",
    "cartridge filter quick change",
    "chiller",
    "circulating pump",
    "combustion air duct",
    "compressor",
    "condensate trap",
    "conical strainer",
    "connection piece",
    "cooler",
    "diaphragm valve",
    "diapragm pump",
    "double bleed and block valve",
    "fine filter",
    "flap with air filter",
    "flexible hose",
    "float valve",
    "four way valve",
    "fuel engine",
    "full bore ball valve",
    "gaging switch",
    "generator",
    "grey loc",
    "heating unit",
    "hose connection",
    "hpu",
    "level switch",
    "line termination",
    "manual chock valve",
    "manually operated valve",
    "min flow control valve",
    "pinch valve",
    "piping special item",
    "plate heat exchanger",
    "process shutdown",
    "provision plant",
    "pump with motor",
    "pump",
    "quick close valve",
    "reducing flange",
    "restrictor",
    "rupture disc",
    "screw down- non-return valve",
    "self acting pressure control valve",
    "self close cock",
    "self contained thermostat valve",
    "shutdown valve",
    "silencer",
    "single nozzle tank cleaning machine",
    "sounding pip-self closing cock",
    "sounding pipe-screw cap",
    "spacer",
    "spade",
    "spectacle blind nc",
    "spectacle blind no",
    "sprint loaded valve",
    "strainer t-type",
    "strainer y-type",
    "strainer",
    "submerged tank cleaning machine",
    "switchboard",
    "swivel joint",
    "temperature indicator",
    "temperature transmitter",
    "temporary strainer",
    "three way valve with motor",
    "three way valve",
    "tie-in point",
    "tower",
    "transfer pump",
    "trap",
    "turbine",
    "vacuum breaker",
    "ventilation fan",
    "ventilation unit"
]

# List 2
list2 = [
    "AIR DRYER",
    "AIR FILTER OR STRAINER",
    "AIR FILTER",
    "AIR LUBRICATOR",
    "AIR VENT WITH FLAME ARRESTOR",
    "ANGLE VALVE",
    "BALL VALVE",
    "BELLMOUTH",
    "BLOWER",
    "BULKHEAD PENETRATION",
    "BUTTERFLY VALVE",
    "CARTRIDGE FILTER QUICK CHANGE",
    "CENTRIFUGAL PUMP",
    "CHECK VALVE",
    "CHILLER",
    "CIRCULATING PUMP",
    "COMBUSTION AIR DUCT",
    "COMPRESSOR",
    "CONDENSATE TRAP",
    "CONICAL STRAINER",
    "CONNECTION PIECE",
    "COOLER",
    "DIAPHRAGM VALVE",
    "DIAPRAGM PUMP",
    "DOUBLE BLEED AND BLOCK VALVE",
    "DUPLEX STRAINER",
    "FINE FILTER",
    "FLAP WITH AIR FILTER",
    "FLEXIBLE HOSE",
    "FLOAT VALVE",
    "FLOW ELEMENT",
    "FLOW INDICATOR",
    "FLOW TRANSMITTER",
    "FOUR WAY VALVE",
    "FUEL ENGINE",
    "FULL BORE BALL VALVE",
    "GAGING SWITCH",
    "GATE VALVE",
    "GENERATOR",
    "GLOBE VALVE",
    "GREY LOC",
    "HEAT EXCHANGER",
    "HEATING UNIT",
    "HOSE CONNECTION",
    "HPU",
    "LEVEL ALARM",
    "LEVEL INDICATOR",
    "LEVEL SWITCH",
    "LEVEL TRANSMITTER",
    "LINE TERMINATION",
    "MANUAL CHOCK VALVE",
    "MANUALLY OPERATED VALVE",
    "MIN FLOW CONTROL VALVE",
    "NEEDLE VALVE",
    "PINCH VALVE",
    "PIPING SPECIAL ITEM",
    "PLATE HEAT EXCHANGER",
    "PLUG VALVE",
    "PRESSURE INDICATOR",
    "PRESSURE TRANSMITTER",
    "PROCESS SHUTDOWN",
    "PROVISION PLANT",
    "PUMP WITH MOTOR",
    "PUMP",
    "QUICK CLOSE VALVE",
    "REDUCER",
    "REDUCING FLANGE",
    "RESTRICTOR",
    "RUPTURE DISC",
    "SCREW DOWN- NON-RETURN VALVE",
    "SCREW PUMP",
    "SELF ACTING PRESSURE CONTROL VALVE",
    "SELF CLOSE COCK",
    "SELF CONTAINED THERMOSTAT VALVE",
    "SHUTDOWN VALVE",
    "SILENCER",
    "SINGLE NOZZLE TANK CLEANING MACHINE",
    "SOLENOID VALVE",
    "SOUNDING PIP-SELF CLOSING COCK",
    "SOUNDING PIPE-SCREW CAP",
    "SPACER",
    "SPADE",
    "SPECTACLE BLIND NC",
    "SPECTACLE BLIND NO",
    "SPRINT LOADED VALVE",
    "STRAINER T-TYPE",
    "STRAINER Y-TYPE",
    "STRAINER",
    "SUBMERGED TANK CLEANING MACHINE",
    "SWITCHBOARD",
    "SWIVEL JOINT",
    "TANK",
    "TEMPERATURE INDICATOR",
    "TEMPERATURE TRANSMITTER",
    "TEMPORARY STRAINER",
    "THREE WAY VALVE WITH MOTOR",
    "THREE WAY VALVE",
    "TIE-IN POINT",
    "TOWER",
    "TRANSFER PUMP",
    "TRAP",
    "TURBINE",
    "VACUUM BREAKER",
    "VENTILATION FAN",
    "VENTILATION UNIT",
  ]

# Convert List 2 to lowercase and merge them
merged_list = list2 + [item.lower() for item in list1]

# Find duplicate items
duplicates = {}
for index, item in enumerate(merged_list):
    if merged_list.count(item) > 1:
        if item not in duplicates:
            duplicates[item] = [index]
        else:
            duplicates[item].append(index)

# Print merged list and duplicates
for item, indices in duplicates.items():
    print(f"Duplicate item: {item}")
    for index in indices:
        print(f"  Found at index {index}: {merged_list[index]}")

# To get the final merged list with duplicates removed:
final_merged_list = list(set(merged_list))